### ISSUE TITLE
Unable to run/debug unit tests

### ISSUE THREAD

**Issue by ttunstall07** [microsoft/PTVS#3313]
I consistently run into issues while debugging unit tests where:

- The test will either continue to run after it's been cancelled or has completed, preventing it or any other test in the project from being ran again

- All unit tests in the project will refresh and certain ones disappear after everything has been reloaded.

Both cases require me to completely restart Visual Studio and has been extremely frustrating given that it happens nearly every 15-20 minutes, sometimes even more often.

**Comment by revz79** [comment]
I have a similar issue: unit tests are discovered correctly but when i try to run them they all fail and the output message is something like this:

```
Message: Failed to import test module: cache_persistence_tests
Traceback (most recent call last):
  File "C:\Program Files\Python36\Lib\unittest\loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'cache_persistence_tests'
```

**Comment by huguesv** [comment]
@revz79 try running the test file with F5/CTRL-F5, it should give you more details on why the import is failing. It's likely an error in the code you are importing.

@ttunstall07 we've made improvements to test discovery recently, I don't recall if they ended up in 15.4 or not. I'll do some testing on cancelling tests to see if I can repro your issue.

**Comment by zooba** [comment]
The improvements to discovery haven't been released yet, and I believe the issue where the Test Window keeps spinning (which was not our fault) will also be fixed in that release. It annoys me too.

**Comment by huguesv** [comment]
I've experimented with cancelling and it appears to work, at least for a simple scenario. I have several tests with `time.sleep` calls in them and when I cancel I see the python.exe process goes away almost immediately (it's not waiting for the current test to complete), and Test Explorer window lets me run tests again.

It looks like this after cancellation:

![image](https://user-images.githubusercontent.com/1696845/32629584-978371ee-c54e-11e7-87bb-d48b5cc9d072.png)

**Comment by ttunstall07** [comment]
I haven't been able to determine a way to consistently reproduce this, but it does seem more prone to happening after I've made changes to the code and/or I'm debugging multiple tests within a short period.

Also, I wouldn't think this would be a factor, but I typically use Shift+F5 to stop debugging a test rather than hitting 'Cancel' within Test Explorer. 

My general debugging settings are below - maybe this will help in reproducing the issue.

![image](https://user-images.githubusercontent.com/17145001/32631994-953b4812-c567-11e7-94f5-b0380630e4be.png)

**Comment by huguesv** [comment]
I did some experiments with this, here are some additional observations.

Stop Debugging does not cancel a test run. The tests continue running, it's just that the debugger is detached.

Hitting cancel when you're debugging tests does not cancel a test run, it stops debugging. Hitting cancel a SECOND time then cancels the run.

I haven't gotten in a situation where I couldn't run tests yet.

I've seen this error a few times when starting tests:
```
[Window Title]
ScriptedSandbox64.exe

[Main Instruction]
ScriptedSandbox64.exe has stopped working

[Content]
A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.

[Close program]```

**Comment by ttunstall07** [comment]
Thanks for continuing to investigate this. I recently did a complete reinstall of Visual Studio along with the new 15.5.1 release. I'll continue to monitor this and report back if I am still having any issues. 

Are you aware of any improvements related to PTVS in this newest release?

**Comment by ttunstall07** [comment]
Thanks for continuing to investigate this. I recently did a complete reinstall of Visual Studio along with the new 15.5.1 release. I'll continue to monitor this and report back if I am still having any issues. 

Are you aware of any improvements related to PTVS in this newest release?

**Comment by huguesv** [comment]
Just critical bug fixes for 15.5 - we've been focused on 15.6 for a few months now.

The first 15.6 preview was released last week: https://blogs.msdn.microsoft.com/pythonengineering/2017/12/07/whats-new-for-python-in-visual-studio-15-6-preview-1/

**Comment by huguesv** [comment]
I just found we have an existing bug for not terminating tests when you stop debugging / hit cancel.
https://github.com/Microsoft/PTVS/issues/826

It sounds like you have additional problems on top of that. What does the UI look like when you get into that bad state?

**Comment by zooba** [comment]
I believe this is a known issue with Test Explorer. It certainly happens to me often enough when working in C# that I don't think it's specific to Python.

**Comment by stefan-muc** [comment]
I experience quite the same as @ttunstall07 with Visual Studio 2017 (15.4.1) with an additional observation: I am unable to run the tests during test discovery. Sometimes test discovery hangs (telling me that another test discovery is running and there aren't more than one allowed - don't have exact wording by hand), thus not allowing me to run tests (»Run All« not blue). I also only could restart Visual Studio to be able to run my tests, and I had to do that often.
Sometimes test discovery jumped in while coding, so I lost information which red tests I still had to fix.

So it got so annoying that I was trying to »debug« this issue by varying parameters. I am now on the latest Preview Version (15.6.1 Preview 1.0) and things got even worse:
 * Normally not even one test gets discovered, test discovery doesn't even run (log output in test window) even after waiting for about a minute.
 * If test discovery runs, only a small portion of my tests get found, around 3-4 tests

I found a critical point is the size of the Python project. If I delete all my sources, I have nearly no problem with test discovery. Of course, nearly no test goes green, but at least they are discovered quite immediately. Only strange thing is: I have 202 tests (15.4.1 told me so), now 380 tests get discovered. Running all tests sometimes changes this number, but it's getting quite stable at that with many tests duplicate in the list.
When not all sources are deleted, I experienced this behavior: Opening solution directly got no tests discovered, opening Visual Studio, waiting for ServiceHub.SettingsHost.exe to start and devenv.exe CPU load dropping to around 0.01 % and then loading solution in most (not all) cases triggered test discovery where some (different) amount of tests got discovered.
I still wasn't able to boil this down to a specific source file, I suppose that it's the amount of files / lines of code that trigger that behavior, which shouldn't be the case.

Environment:
Visual Studio 2017 (15.6.1 Preview 1.0)
Python 3 (3.6.4) (Python 2.7.9 installed parallel, but Tests use Python 3 - I have a test for that which goes green)

Project:
Around 50 files in 10 folders
Around 200 tests in 45 files (and counting)


Hope this helps for further investigation. Hope to see test discovery running again soon!

**Comment by zooba** [comment]
@stefan-muc Just to clarify, are you on "15.6 Preview 1" (which you installed a few months ago and haven't updated) or are you on "15.6.1" (which was the latest update just a few days ago)?

We never release previews of "x.y.1" releases, but it's important for us to know which version you are using. Help/About will show it near the top-left.

**Comment by stefan-muc** [comment]
@zooba: Neither nor. I'm on exact the version I have written, released March 8, 2018 - Visual Studio 2017 version 15.6.1 Preview 1 - see release notes: https://docs.microsoft.com/de-de/visualstudio/releasenotes/vs2017-Preview-relnotes#15.6.1%20Preview%201

**Comment by stefan-muc** [comment]
By the way, I got the logs from the deadlock-situation (with 15.4.1) where I can't run tests anymore and have to restart Studio. In this situation, out of nowhere the test discovery starts and never finishes - the green short bar runs through test explorer and stays like that, CPU load of devenv.exe is around 0.80 % (I waited 10 minutes for it to finish...)

```
[2018-03-13 08:46:35 Informational] ========== Discover test finished: 5 found (0:00:00.0270054) ==========
[2018-03-13 08:46:49 Informational] ------ Discover test started ------
[2018-03-13 08:46:49 Informational] ------ Discover test started ------
[2018-03-13 08:46:49 Informational] ------ Discover test started ------
[2018-03-13 08:46:49 Informational] ========== Discover test finished: 9 found (0:00:00.0545109) ==========
[2018-03-13 08:46:49 Informational] ========== Discover test finished: 2 found (0:00:00.0660132) ==========
[2018-03-13 08:46:49 Informational] ------ Discover test started ------
[2018-03-13 08:46:49 Informational] ========== Discover test finished: 2 found (0:00:00.4075815) ==========
[2018-03-13 08:46:49 Informational] ========== Discover test finished: 7 found (0:00:00.4410882) ==========
[2018-03-13 08:46:49 Informational] ------ Discover test started ------
[2018-03-13 08:46:49 Informational] ========== Discover test finished: 1 found (0:00:00.4465893) ==========
[2018-03-13 08:46:50 Informational] ------ Discover test started ------
[2018-03-13 08:46:50 Informational] ========== Discover test finished: 3 found (0:00:00.8086617) ==========
[2018-03-13 08:46:50 Informational] ------ Discover test started ------
[2018-03-13 08:46:50 Informational] ------ Discover test started ------
[2018-03-13 08:46:50 Informational] ------ Discover test started ------
[2018-03-13 08:46:50 Informational] ------ Discover test started ------
[2018-03-13 08:46:50 Error] A discovery request is already in progress. Only one active discovery request is supported.
[2018-03-13 08:46:50 Informational] ========== Discover test finished: 0 found (0:00:00.0605121) ==========
[2018-03-13 08:46:50 Informational] ------ Discover test started ------
```

**Comment by zooba** [comment]
@stefan-muc You're right, we briefly had 15.6.1 available in VS Preview (it was exactly the same as the stable 15.6.1).

That has now been updated to 15.7 Preview 1 in the last hour or so. Could you update to that and see if the fixes in the newer version help?

I'm still of the opinion that this is not caused by Python, and the test explorer team has resolved some issues recently.

**Comment by stefan-muc** [comment]
@zooba 
I am unable to test this as 15.7 Preview 1 doesn't load my project anymore. The Migration Report tells me:
The application which this project type is based on was not found. Please try this link for further information: https://go.microsoft.com/fwlink/?LinkId=660751&projecttype=888888A0-9F3D-457C-B088-3A5042F75D52

The last time I had a compareable problem after Studio Upgrade was with 2017 Upgrade where I had to install Python Tools (which the Upgrade didn't do) but this time the Setup Tool tells me Python Tools are installed.

**Comment by stefan-muc** [comment]
@zooba 
Now as 15.7.0 Preview 2.0 is out I am able to test again. Test discovery now works a little bit - mostly I get four tests discovered (always the same four), sometimes six. So It still isn't fixed.

```
[2018-03-26 09:25:14 Informational] ------ Load Playlist started ------
[2018-03-26 09:25:14 Informational] ========== Load Playlist finished (0:00:00.0075075) ==========
[2018-03-26 09:25:17 Informational] ------ Discover test started ------
[2018-03-26 09:25:18 Warning] A test with the same name 'tests\test_helpersMyThing.py::Test_helpersMyThing::test_helpersMyThinggetInformationFromString_returnsCorrectStrings_forUsualStrings' already exists. This test is not added to the test window.
[2018-03-26 09:25:18 Warning] A test with the same name 'tests\test_helpersMyThing.py::Test_helpersMyThing::test_helpersMyThinggetInformationFromString_returnsCorrectStrings_forSpecialStrings' already exists. This test is not added to the test window.
[2018-03-26 09:25:18 Warning] A test with the same name 'tests\test_helpersMyThing.py::Test_helpersMyThing::test_helpersMyThinggetInformationFromString_doesntAcceptInvalidStrings' already exists. This test is not added to the test window.
[2018-03-26 09:25:18 Warning] A test with the same name 'tests\test_helpersMyThing.py::Test_helpersMyThing::test_helpersMyThinggetInformationFromString_returnsNoAppendix_forRubbishInAppendix' already exists. This test is not added to the test window.
[2018-03-26 09:25:18 Informational] ========== Discover test finished: 8 found (0:00:01.507506) ==========
[2018-03-26 09:25:18 Informational] ------ Discover test started ------
[2018-03-26 09:25:19 Informational] ========== Discover test finished: 4 found (0:00:00.57057) ==========
[2018-03-26 09:25:19 Informational] ------ Discover test started ------
[2018-03-26 09:25:20 Informational] ========== Discover test finished: 6 found (0:00:00.722722) ==========
```

With one start I got this exception:
```
[2018-03-26 09:24:27 Error] System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Microsoft.VisualStudio.TestWindow.Controller.TestPlatformProvider.UpdateTestPlatform(Lazy`1 testPlatform)
   at Microsoft.VisualStudio.TestWindow.Controller.TestPlatformProvider.GetTestPlatformV2()
```
but I wasn't able to reproduce it.

What can I do to help to track down the bug?

**Comment by huguesv** [comment]
I merged a fix today for the warning of test with the same name. It will be in Preview 4.
That `NullReferenceException` exception doesn't show Python in the call stack, so that may not be our issue.

**Comment by mozarthasse** [comment]
I had the same issue with VS 2017 at least up to version 15.6.6 and it was really, _**really**_ annoying. It happened **everytime** I debugged my code, stopped to _make a change_ and tried to debug it _again_. It stopped occurring after I changed a couple of my debugging options to match **exactly** the ones suggested by ttunstall07 on 9 Nov 2017. 
I can debug my code now, but this should work with any debugging setting. My guess is that it has something to do with that "managed compatibility mode" option.

**Comment by stefan-muc** [comment]
I'm now on Visual Studio 15.8.0 Preview 1.0 (guess that includes the "Preview 4" changes that @huguesv mentioned)

I didn't have much time o test, but it seems as test discovery got a little better.

First run: (and no tests discovered)
```
[2018-05-08 10:07:32 Informational] ------ Discover test started ------
[2018-05-08 10:07:32 Informational] ------ Discover test started ------
[2018-05-08 10:07:35 Error] The active Tests Discovery was aborted.
[2018-05-08 10:07:35 Error] The active Tests Discovery was aborted.
[2018-05-08 10:07:35 Informational] ========== Discover test finished: 0 found (0:00:03.1735) ==========
[2018-05-08 10:07:35 Informational] ========== Discover test finished: 0 found (0:00:03.1735) ==========
[2018-05-08 10:07:39 Informational] ------ Discover test started ------
[2018-05-08 10:07:40 Error] The active Tests Discovery was aborted.
[2018-05-08 10:07:40 Informational] ========== Discover test finished: 0 found (0:00:01.204) ==========
[2018-05-08 10:07:40 Informational] ------ Discover test started ------
[2018-05-08 10:07:40 Error] The active Tests Discovery was aborted.
[2018-05-08 10:07:40 Informational] ========== Discover test finished: 0 found (0:00:00.382) ==========
[2018-05-08 10:07:46 Informational] ------ Discover test started ------
[2018-05-08 10:07:46 Error] The active Tests Discovery was aborted.
[2018-05-08 10:07:46 Informational] ========== Discover test finished: 0 found (0:00:00.2555) ==========
[2018-05-08 10:07:46 Informational] ------ Discover test started ------
[2018-05-08 10:07:47 Error] The active Tests Discovery was aborted.
[2018-05-08 10:07:47 Informational] ========== Discover test finished: 0 found (0:00:01.1065) ==========
```

Second run: (but all tests found)
```
[2018-05-08 10:09:14 Informational] ------ Discover test started ------
[2018-05-08 10:09:14 Informational] ------ Discover test started ------
[2018-05-08 10:09:16 Error] System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Microsoft.VisualStudio.TestWindow.Controller.TestPlatformProvider.UpdateTestPlatform(Lazy`1 testPlatform)
   at Microsoft.VisualStudio.TestWindow.Controller.TestPlatformProvider.GetTestPlatformV2()
[...]
```

With more tries it discovers all my tests quite reliably and without error output.
Didn't try the other bugs reported here - hope I find some time for that.

**Comment by stefan-muc** [comment]
Today I installed 15.7.4 and tested again, now Test discovery works reliably (after a delay of about 10 seconds after project is loaded), and in the end always reports 302 tests (count goes from 304 -> 371 -> 328 -> 302, exact numbers differ sometimes, but those appear most of the time)

What's strange that some tests are double discovered - but only one instance passes, the other one fails (_Message: type object 'TestCaseXXX' has no attribute 'test_MyTestName'_) - and if a test re-discovery kicks in, the state of the failing test switches to "Not Run Tests", the passed one stays in passed state.

So it's getting better and better, and so 15.7.4 is a version I can use in productive use :)

**Comment by PHuhn** [comment]
I am running 15.8.7 Visual Studio and my tests are not being discovered.  I create a test from the template and it registers **test_A**.  I add my own test and it does not discover the test.  I completely change the name of **test_A** and it still has **test_A** in the list of tests.  If I only change the **A** in the name then it discovers the new name.  If I change **test_A** to  **Test_A**, it does NOT discover it.

**Comment by huguesv** [comment]
We've rewritten test discovery in 16.3 to run unittest module to do the discovery. Given most of the comments here applied to discovery (save for cancel issue filed at https://github.com/microsoft/PTVS/issues/826) then I'm going to close this.

If you encounter further discovery errors in 16.3 Preview 2 or later, please open a new issue.
