### ISSUE TITLE
Class and Members dropdowns not working properly.

### ISSUE THREAD

**Issue by mrolle45** [Microsoft/PTVS#3317]
When I open a solution and open a Py module in one of its projects, I get two dropdown boxes at the top of the source file window.  However, the one for classes has nothing in it until I put my cursor somewhere inside some class.  Then all the class names appear.
Then, I find that the box for classes has nothing in it.  When I put the cursor somewhere in one of the slass' methods, then the method names appear.  Further, when I put the cursor in some other class, that class' names also appear correctly.
Another problem is that when I open the solution, and one of the modules is the active window, then the dropdowns don't appear at all.  The only way I can get them to appear is to close the tab and reopen the module.  If I activate a different tab, I get the dropdowns.

**Comment by huguesv** [comment]
Some of these issues (like missing dropdowns) have been fixed in https://github.com/Microsoft/PTVS/pull/3132 and will be available in an upcoming release.
I'll try to repro your repro with classes being empty.

**Comment by mrolle45** [comment]
Looking at #3132 it looks like you've already made fixes to two of my observed problems, and the one you're looking at is that the classes list is empty until the cursor is placed inside a class.  Also be sure and check out the second part of that, namely, the methods lists all being empty until the cursor is placed inside any method of any class.  And while you're at it, see about my enhancement request #3318.  Thanks.

**Comment by huguesv** [comment]
The issue with the classes list being empty and methods list being empty until you place the cursor inside a class/method is still there.

**Comment by huguesv** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/435346/python程序多数不能显示全局对象列表与成员列表.html

**Comment by FettLuo** [comment]
The problem of VS2019 still exists.
My research is that there is a problem with the VS cache for the a.py file that went wrong.
There is no problem with me copying the same content to another file b.py. And clean up the a.py, enter the new object information, still list the function names in the old content, and click VS will crash.

**Comment by FettLuo** [comment]
Rename the problem file will be fixed.but rename back still is error.
