### ISSUE TITLE
Cannot create new classifier project(cookiecutter)

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#4955]
VS Version: 28426.127.d16.0stg
Python Tool Version: 16.0.18354.1

Repro step:
1. Open VS
2. Click "File->New->Project->Python->Classifier Project(cookiecutter)"
3. Click "Next->Create"

Expect Result:No error popup

Actual Result:Error dialog is popup
![image](https://user-images.githubusercontent.com/39871640/50536547-85d47400-0b90-11e9-851e-11fbc5238886.png)

**Comment by huguesv** [comment]
Internal bug 762352 (covers both the error message and the fact that the start dialog stays up)

This is to be fixed by the VS IDE team.

**Comment by huguesv** [comment]
Workaround is to manually dismiss the error message and the startup dialog.

**Comment by huguesv** [comment]
This is broken again.

**Comment by linette-zyy** [comment]
This issue also occurred when create new project from existing code.
![image](https://user-images.githubusercontent.com/59192491/78763309-8c6ab180-79b7-11ea-9548-3dd5a2c4b385.png)

**Comment by huguesv** [comment]
Fixed in 16.7

**Comment by ete1729** [comment]
Nice to hear it is fixed in 16.7. I am currently in 16.6.3 and I cannot create a solution or a project.
So, what is your solution ?

**Comment by huguesv** [comment]
If you try to create the project (ML project or From Existing Python Code project types) before the VS main window is up, then it aborts after the error and does nothing.

But if you dismiss the start window, by clicking 'continue without code', then you can do File->New->Project and it will work fine. The error will still appear, but you can dismiss it.

**Comment by RedactedProfile** [comment]
Will the release of 16.7 also fix the same error when creating a Node solution from existing sources?

**Comment by huguesv** [comment]
@RedactedProfile Yes, I have just checked and it works for Node on 16.7

**Comment by RedactedProfile** [comment]
@huguesv thank you!

**Comment by Regnever** [comment]
still bug in newest version
![image](https://user-images.githubusercontent.com/62653232/88598502-9e21b300-d093-11ea-8ad9-d37a6d7eaf25.png)

**Comment by zhouwangyang** [comment]
This problem was not happened in 16.8.0
![image](https://user-images.githubusercontent.com/39871640/89760528-2b96e580-db1f-11ea-8ea9-82b527866012.png)
