### ISSUE TITLE
Failed to launch debug adapter in romote debugging with debugpy.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6369]
Python Environment:
![image](https://user-images.githubusercontent.com/39871640/105473243-d8cd7680-5cd7-11eb-837a-3146685248e8.png)

**Steps to Reproduce**
1.Typing code in .py and set breakpoint in the code.
```
input('>')
print('hello')
```
2.Install "debugpy" in the current python environment.
3.In command prompt(right-click the python environment and select "Open Command Prompt Here…"), execute:
python -m debugpy --listen 127.0.0.1:4022 C:\Users\vwazho\source\repos\PythonApplication1\PythonApplication1\PythonApplication1.py
4. Launch VS and Debug > Attach to Process, in dialog:
		a. Select connection type with Python remote(ptvsd)
		b. Connection target with 127.0.0.1:4022
		c. In Available processes list, select the appropriate python.exe, click "Attach"
5. Type enter in the console
6.Check that it stops at the breakpoint
**Expected behavior**
remote attach successfully with no errors

**Actual behavior**
error dialog pop up when attaching.
![image](https://user-images.githubusercontent.com/39871640/105473077-a459ba80-5cd7-11eb-99a3-f26fe77dfe35.png)

**Comment by judej** [comment]
@int19h, could you look at this please?

**Comment by AdamYoblick** [comment]
@int19h I believe this is due to some parsing of the adapterLaunchInfo I added to support passing variable presentation options to the debugger upon launch. I tested when launching through the VS but I didn't test when debugging by attaching to a remote process, which is causing this error.

Specifically, in DebugAdapterLauncher.cs, line 207:

```
try {
                var adapterLaunchInfoJson = JObject.Parse(adapterLaunchInfo.LaunchJson);
                AddVariablePresentationOptions(adapterLaunchInfoJson, launchJson);
            } catch (JsonReaderException) {
                // this should never happen
                Debug.Fail("adapterLaunchInfo is not valid json");
            }
```

This bug is caused by adapterLaunchInfo.LaunchJson being null, which I didn't think could happen. Bad assumption on my part. I'll get it fixed.

**Comment by AdamYoblick** [comment]
This bug is fixed locally, but the variable presentation options aren't being passed along if the `adapterLaunchInfo.LaunchJson` is null. I need to fix that as well, will get a PR up soon.

**Comment by AdamYoblick** [comment]
Actually, I don't think it's possible to pass along the variablePresentation options when attaching, because the debugger has already been launched. So I think a simple null check is the right fix here.

**Comment by AdamYoblick** [comment]
@zhouwangyang Thank you for catching this regression!

**Comment by int19h** [comment]
Even in the attach scenario, debugpy is still getting a request ("attach") with debug configuration, so it should be possible to specify this property there, and it should respect that if it's present. I think it's rather a problem with the way this is currently plumbed in VS. 

I think it would be beneficial to take the quick fix first, just to remove the breakage - but then we need to figure out how to fix it right so that the setting actually works. I can investigate that.

**Comment by AdamYoblick** [comment]
My comment was wrong, we definitely can read from the options page. The PR has been updated with the new logic to do so. :)
