### ISSUE TITLE
VS-2022 "Python/Native Debugging" not working after being brought back from missing

### ISSUE THREAD

**Issue by flexorx** [microsoft/PTVS#7260]
After a clean install VS-2022 and "returning back" "Python/Native Debugging", as suggested [here](https://github.com/microsoft/PTVS/issues/6712) with copying files from `.../v16/...` to `.../v17/...`, the debugging feature doesn't work in Python code, and the breakpoints won't be triggered in Python code at all. 

**Steps to Reproduce**
1. Make sure to remove all Pythons from Windows. That is to make sure we are testing everything against same vanilla Python.
2. Install Python 3.6 x64 with Web Installer, all default locations, but check to install debug symbols and everything else in the "Additional" settings. We use 3.6 here to avoid these things with venv occurring from 3.8 and onwards.
3. Fresh-install VS-2017, VS-2019 and VS-2022. DO NOT install Python with Visual Studio: this is to guarantee that all three different VS are tested against exact same Python, which we installed previously.
4. Fix VS-2022 "Python/Native Debugging" missing, as described in https://github.com/microsoft/PTVS/issues/6712.
5. Clone my projects showing the issue: https://github.com/flexorx/simple_cpp_python. These are 3 identical projects, but each set to the right VS target.
6. Change the paths in projects to the right ones for your Python 3.6 installed location, i.e. `c:\Users\x1\AppData\Local\Programs\Python\Python36\include\` to your location, and `c:\Users\x1\AppData\Local\Programs\Python\Python36\libs\` to yours.
7. See the video attached below, follow how the breakpoints are set, and go through all three projects to verify that the Python breakpoint is hit in VS-2017 and VS-2019, but not in VS-2022.

![StrangeThing2](https://user-images.githubusercontent.com/49031207/206269314-54865818-108e-47c5-8b6f-8eb210342173.gif)

**Expected behavior**

Debugging with breakpoints work both in Python and in C++ in "Python/Native Debugging" in VS-2022.

**Sample Code**

https://github.com/flexorx/simple_cpp_python

**Comment by LazyDodo** [comment]
> Here's a great repro which uses Python 3.6, which means that python 3.10+ is not the cause of this.
> https://github.com/microsoft/PTVS/issues/7260

disclaimer: total gut feeling but given I was in this area recently for 3.10 support i have a good feeling this is correct

3.6 isn't supported, according to
```
        private Int32Proxy GetTracingPossible(PythonRuntimeInfo pyrtInfo, DkmProcess process) =>
            pyrtInfo.LanguageVersion switch {
                PythonLanguageVersion.V37 or PythonLanguageVersion.V38 =>
                    _pyrtInfo.GetRuntimeState().ceval.tracing_possible,
                PythonLanguageVersion.V39 =>
                    PyInterpreterState.GetInterpreterStates(process).First().ceval.tracing_possible,
                _ =>
                    throw new InvalidOperationException($"Unsupported Python version: {pyrtInfo.LanguageVersion}")
            };
```
this will throw an exception on py36 which means

```
        public unsafe void RegisterTracing(PyThreadState tstate) {
            tstate.use_tracing.Write(1);
            tstate.c_tracefunc.Write(_traceFunc.GetPointer());
            var pyTracingPossible = GetTracingPossible(_pyrtInfo, _process);
            pyTracingPossible.Write(pyTracingPossible.Read() + 1);
            _isTracing.Write(1);
        }
```
that last line there will never be executed which likely is breaking debugging for py36

**Comment by AdamYoblick** [comment]
Thanks @LazyDodo for the details on 3.6 not working :)

I'm going to get the installer issues fixed with those files not going to the right place. Once that's done, I'll try to repro these exact steps with python 3.9, which is technically the highest version we _officially_ support. If it still doesn't work, we will investigate why and get it fixed.

**Comment by AdamYoblick** [comment]
I've fixed the install path problem, so I'm moving on to this issue now. 😄

**Comment by AdamYoblick** [comment]
Also I just want to say @flexorx - thank you for the amazing repro steps and gif. This helps immensely.

**Comment by StellaHuang95** [comment]
Another duplicate issue with Python/Native debugging: https://github.com/microsoft/PTVS/issues/7182

**Comment by int19h** [comment]
After fixing the checkbox, are there any issues still observed on supported Python versions (3.7-3.9)?

**Comment by AdamYoblick** [comment]
I'm in the process of repro'ing now, I'll know for sure tomorrow. Got pulled into some compliance investigations and didn't have time to finish the repro today 😄

**Comment by flexorx** [comment]
Thanks for looking into the issue @AdamYoblick @int19h @StellaHuang95 !
There's a clean laptop laying nearby, so I have a good chance to verify the fix on a clean environment very soon.

**Comment by AdamYoblick** [comment]
I can't repro this locally using python 3.9.13, I'm able to hit both breakpoints. I got prompted for python interpreter symbols and debug binaries, which I installed through the python installer, per the instructions at https://learn.microsoft.com/en-us/visualstudio/python/debugging-symbols-for-mixed-mode-c-cpp-python?view=vs-2022.

I had to change some of the paths in the spam.vcxproj, as you mentioned. I also had to remove the non-existing virtual environment from the PythonApplication.pyproj and re-create it through visual studio. Once I did those things, everything worked like it should. See below:

**Comment by AdamYoblick** [comment]
Can you try again with python 3.9? A [previous comment](https://github.com/microsoft/PTVS/issues/7260#issuecomment-1439111509) mentioned why this would be broken for 3.6, and we don't officially support 3.6 anymore.

**Comment by LazyDodo** [comment]
This is expected behavior, anything outside of python 3.7-3.9 isn't officially supported. 

3.10 isn't terribly difficult to get working unofficially but does require building from source

```
public unsafe void RegisterTracing(PyThreadState tstate) {
    //tstate.use_tracing.Write(1);
    tstate.c_tracefunc.Write(_traceFunc.GetPointer());
    //var pyTracingPossible = GetTracingPossible(_pyrtInfo, _process);
    //pyTracingPossible.Write(pyTracingPossible.Read() + 1);
    _isTracing.Write(1);
}
```
did the trick last time i looked at this

**Comment by flexorx** [comment]
@LazyDodo thanks! I've also tried with 3.9, the official one shipped with VS installation (I think it is 3.9.13). That doesn't work either. It's enough to just create a flat Python Application project and set a check "Native Debugging" in project properties. This will make Python debugger non-functional.

**Comment by LazyDodo** [comment]
https://github.com/microsoft/PTVS/wiki/Build-and-Debug-Instructions-for-PTVS

**Comment by blargelJim** [comment]
I've just tried something similiar to this:
Create a C++ application that embeds python 3.11 and simply loads and runs a python function from a file.
Then try to enable mixed mode debugging.

The breakpoints in C++ work fine, but the breakpoints in the python module being loaded are never hit.
Am I correct to believe that Visual Studio 2022 (17.7.2 community edition) dose'nt support mixed mode debugging for C++/python with python 3.11?
Its very hard to find any information on what version of python is supported in this scenario on microsoft homepage - if anyone from microsoft reads this can you please help clarify if Im correct or not? And a suggestion is to add more information about this on your documentation (https://learn.microsoft.com/en-us/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio?view=vs-2022#enable-mixed-mode-debugging-in-a-cc-project)

**Comment by int19h** [comment]
This is correct - Python 3.11 has many changes in Python internals around stuff like frame objects, and would require a major update to the mixed-mode debugger to support.

**Comment by NeilWP** [comment]
I am confused  - debug is a fact of development - how can it be that such an essential aspect of an IDE is allowed to fail  in  arelease version of the IDE or the components delivreing that functionality for so long  
[https://stackoverflow.com/questions/56794940/vscode-why-isnt-debugger-stopping-at-breakpoints](https://stackoverflow.com/questions/56794940/vscode-why-isnt-debugger-stopping-at-breakpoints)  is from 2019 and here we see it still being an issue  in 2025 
[https://github.com/microsoft/debugpy/issues/1893](https://github.com/microsoft/debugpy/issues/1893)
